name: "Create a feature build"

on:
  issue_comment:
    types: [created]
  pull_request:
    branches:
      - main

jobs:
  fb:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '@pmmbot create-fb')
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}" >> $GITHUB_ENV
        id: extract_branch        

      - name: Checkout pmm-submodules
        uses: actions/checkout@v3
        with:
          repository: percona-lab/pmm-submodules
          ref: PMM-2.0

      - name: Create a FB
        run: |
          echo "Creating a feature build for branch: $BRANCH"
          
          cat <<EOF > ci.yml
          deps:
            - name: pmm
              branch: $BRANCH
          EOF
          
          cat ci.yml
          
          # create a branch with the same name
          git checkout -b ${{ steps.extract_branch.outputs.branch }}
          git commit -a -m "FB[bot]: ${{ steps.extract_branch.outputs.branch }}"
          # print debug info
          git branch
          git log --oneline -n 10
