name: "Pmmbot"

on:
  issue_comment:
    types: [created]
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to build the feature from"
        required: true
        type: string    

jobs:
  feature-build:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    # && startsWith(github.event.comment.body, '@pmmbot create-fb')
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}" >> $GITHUB_ENV

      - name: Checkout pmm-submodules
        uses: actions/checkout@v3
        with:
          repository: percona-lab/pmm-submodules
          ref: PMM-2.0

      - name: Create a branch
        run: |
          echo "Creating a feature build for branch: $BRANCH"
          
          cat <<EOF > ci.yml
          deps:
            - name: pmm
              branch: $BRANCH
          EOF
          
          cat ci.yml
          
          # create a branch with the same name
          git checkout -b $BRANCH
          git commit -a -m "FB[bot]: $BRANCH"
          # print debug info
          git status
          git log --oneline -n 10
